### ISSUE TITLE
[Bug] Protainer CE kubernetes API Error

### ISSUE THREAD

**Issue by ForsakenRei** [benphelps/homepage#1009]
### Description

I have a portainer instance running on TrueNAS Scale, where all the containers are running in kubernetes env. The error message from that widget is
```Something went wrong.
TypeError: c.filter is not a function
at l ({my host machine local domain}/_next/static/chunks/8019.99640e425086c02c.js:1:1088)
    at h ({my host machine local domain}/_next/static/chunks/8851-2e733d9d318b32dc.js:1:12200)
    at n ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:9835)
    at G ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:18710)
    at div
    at li
    at D ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:21743)
    at ul
    at O ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:25280)
    at div
    at R ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:25567)
    at div
    at div
    at re ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:38824)
    at n ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:9835)
    at {my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:88005
    at te ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:36860)
    at div
    at div
    at ie ({my host machine local domain}/_next/static/chunks/pages/index-12b532570623b60a.js:1:42705)
    at a ({my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:15041)
    at s ({my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:15598)
    at u ({my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:14473)
    at {my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:88005
    at {my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:13754
    at l ({my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:1461)
    at n ({my host machine local domain}/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:5971)
    at r ({my host machine local domain}/_next/static/chunks/main-d2b206db40ae9853.js:1:6948)
    at Y ({my host machine local domain}/_next/static/chunks/main-d2b206db40ae9853.js:1:9190)
    at ie ({my host machine local domain}/_next/static/chunks/main-d2b206db40ae9853.js:1:11830)
```

I use the `yaml` below which works for another two portainer I have on different machines, the differences I can tell is the one on TrueNAS are not running docker but kubernetes, and it's not using the default 9443 port. I'm not sure if they are relevant though.

If I run `docker exec homepage ping {my NAS IP}:{port} there is no loss. 
If I run `curl -L -k -H 'X-Api-Key:{mykey}' '{my NAS IP}:{port}/api/endpoints/1/docker/containers/json'` the output is
```{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:ix-portainer-ce:portainer-ce\" cannot get path \"/containers/json\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}%  
```
All other apps on my NAS works fine with homepage. The other issue I found is about Jellyfin so it might be different.

### Steps to reproduce

1. Get a portainer instance on top of kubernetes
2. Generate access token for my account
3. Follow the documentation to add widget to `widget.yaml`.

### homepage version

v0.6.7

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        icon: portainer.png
        href: {my NAS local domain}
        widget:
          type: portainer
          url: {my NAS local domain}
          env: 1
          key: {my access token}
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by ForsakenRei** [comment]
> The curl is showing a 403 forbidden. Can you make sure the auth is correct and has sufficient privileges?

The key is correct, I regenerated a new one when I found the issue but still not working. I have only 1 user for that portainer instance so I think it should has sufficient privileges.

Does it have anything to do with kubernetes rather than docker?

**Comment by shamoon** [comment]
Definitely could be, I have never tried kubernetes portainer. The 403 is kinda suspicious but I suppose you could check to see if any other API endpoints work ( https://app.swaggerhub.com/apis/portainer/portainer-ce/2.17.0#/ ). If they do then yea it would point to incompatibility with kubernetes portainer. Just looking at it I kind wouldn't expect `api/endpoints/1/docker/containers/json` to work in a k8s setup, but a 403 is weird, I'd expect a more sensible response

**Comment by ForsakenRei** [comment]
> Definitely could be, I have never tried kubernetes portainer. The 403 is kinda suspicious but I suppose you could check to see if any other API endpoints work ( https://app.swaggerhub.com/apis/portainer/portainer-ce/2.17.0#/ ). If they do then yea it would point to incompatibility with kubernetes portainer. Just looking at it I kind wouldn't expect `api/endpoints/1/docker/containers/json` to work in a k8s setup, but a 403 is weird, I'd expect a more sensible response

The API endpoint should be `kubernetes/application/json` if I understand it correctly. And it does give me the same 403, which looks like a permission issue. If I just use some random string as token then the return will be unauthorized, so authorization part should be fine.
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:ix-portainer-ce:portainer-ce\" cannot get path \"/application/json\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}%
```

Originally I thought I might missed some setting to let k8s accessible from external but then I realized my jellyfin is on k8s as well but homepage can grab what it need without any issue...
