### ISSUE TITLE
[Bug] Application error after filling in settings.yaml

### ISSUE THREAD

**Issue by HvRibbecK** [benphelps/homepage#1039]
### Description

Currently homepage gives the "Application error: a client-side exception has occurred (see the browser console for more information)." after I write something in settings.yaml (e.g. title: test).

![image](https://user-images.githubusercontent.com/55252063/220663100-a3930cb0-9b4b-455b-9829-03492a15346c.png)

### Steps to reproduce

1. Write something in settings.yaml
2. Refresh Homepage

### homepage version

v0.6.8

### Installation method

Docker

### Configuration

```yaml
Full default config, I just changed some Group names and added two test services.
```

### Container Logs

```Listening on port 3000

[2023-02-22T14:57:04.569Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T14:57:04.573Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T14:57:20.122Z] error: expected a single document in the stream, but found more

[2023-02-22T14:57:20.701Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T14:57:20.701Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T14:57:20.747Z] error: <index> YAMLException: expected a single document in the stream, but found more

    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2812:9)

    at getSettings (/app/.next/server/chunks/552.js:60:58)

    at getStaticProps (/app/.next/server/pages/index.js:1988:100)

    at Object.renderToHTML (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/render.js:386:26)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async doRender (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:669:38)

    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:778:28)

    at async /app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/response-cache/index.js:80:36

[2023-02-22T14:57:20.919Z] error: expected a single document in the stream, but found more

[2023-02-22T14:57:21.402Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T14:57:21.402Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T15:01:13.331Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T15:01:13.331Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T15:01:14.384Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T15:01:14.385Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T15:01:22.499Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T15:01:22.499Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T15:02:51.028Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T15:02:51.029Z] error: YAMLException: expected a single document in the stream, but found more

[2023-02-22T15:02:52.029Z] error: Failed to load settings.yaml, please check for errors

[2023-02-22T15:02:52.029Z] error: YAMLException: expected a single document in the stream, but found more
```

### Browser Logs

![image](https://user-images.githubusercontent.com/55252063/220663100-a3930cb0-9b4b-455b-9829-03492a15346c.png)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
As this project is not entirely broken for everyone it would seem you have an error in the yaml or your docker setup, don’t you think?

**Comment by nerdspar** [comment]
I'm running into the same issue. Clean install on TrueNAS Scale. All other containers work great. 

Seems like /app/ is owned by node:node, config/ by root:dockeruser, and settings.yml by dockeruser:dockeruser and I can't seem to change that.
