### ISSUE TITLE
[Bug] Configuration files are create with user root

### ISSUE THREAD

**Issue by myhrmans** [benphelps/homepage#1046]
### Description

Supplying PUID and PGID to the docker container does still create the files as root breaking the setup.

Supplying them as environment variables should create it as user 1000 and with group 1000 if I understand it correctly, but files are still created as root.

### Steps to reproduce

Use the compose configuration that is supplied in a fresh install of homepage

### homepage version

v0.6.9

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    #  - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
```

### Container Logs

homepage    | [2023-02-24T12:02:11.569Z] error: undefined
homepage    | [2023-02-24T12:02:11.571Z] info: widgets.yaml was copied to the config folder
homepage    | [2023-02-24T12:02:11.577Z] error: undefined
homepage    | [2023-02-24T12:02:11.578Z] error: undefined
homepage    | [2023-02-24T12:02:11.578Z] error: undefined
homepage    | [2023-02-24T12:02:12.450Z] error: undefined
homepage    | [2023-02-24T12:02:12.451Z] error: undefined
homepage    | [2023-02-24T12:02:12.451Z] error: undefined
homepage    | [2023-02-24T12:02:13.230Z] error: undefined
homepage    | [2023-02-24T12:02:13.231Z] error: undefined
homepage    | [2023-02-24T12:02:13.232Z] error: undefined
homepage    | [2023-02-24T12:02:18.247Z] error: undefined
homepage    | [2023-02-24T12:02:18.249Z] error: undefined
homepage    | [2023-02-24T12:02:23.246Z] error: undefined
homepage    | Listening on port 3000
homepage    | Error: ENOENT: no such file or directory, open '/app/config/settings.yaml'
homepage    |     at Object.openSync (node:fs:600:3)
homepage    |     at readFileSync (node:fs:468:35)
homepage    |     at getSettings (/app/.next/server/chunks/4210.js:59:72)
homepage    |     at init (/app/.next/server/chunks/3471.js:32:93)
homepage    |     at createLogger (/app/.next/server/chunks/3471.js:99:5)
homepage    |     at /app/.next/server/chunks/5617.js:107:81 {
homepage    |   errno: -2,
homepage    |   syscall: 'open',
homepage    |   code: 'ENOENT',
homepage    |   path: '/app/config/settings.yaml'
homepage    | }
homepage    | settings.yaml was copied to the config folder
homepage    | settings.yaml was copied to the config folder
homepage    | Error: ENOENT: no such file or directory, open '/app/config/settings.yaml'
homepage    |     at Object.openSync (node:fs:600:3)
homepage    |     at readFileSync (node:fs:468:35)
homepage    |     at getSettings (/app/.next/server/chunks/4210.js:59:72)
homepage    |     at init (/app/.next/server/chunks/3471.js:32:93)
homepage    |     at createLogger (/app/.next/server/chunks/3471.js:99:5)
homepage    |     at /app/.next/server/chunks/5617.js:107:81 {
homepage    |   errno: -2,
homepage    |   syscall: 'open',
homepage    |   code: 'ENOENT',
homepage    |   path: '/app/config/settings.yaml'
homepage    | }
homepage    | Error: ENOENT: no such file or directory, open '/app/config/settings.yaml'
homepage    |     at Object.openSync (node:fs:600:3)
homepage    |     at readFileSync (node:fs:468:35)
homepage    |     at getSettings (/app/.next/server/chunks/4210.js:59:72)
homepage    |     at init (/app/.next/server/chunks/3471.js:32:93)
homepage    |     at createLogger (/app/.next/server/chunks/3471.js:99:5)
homepage    |     at /app/.next/server/chunks/5617.js:107:81 {
homepage    |   errno: -2,
homepage    |   syscall: 'open',
homepage    |   code: 'ENOENT',
homepage    |   path: '/app/config/settings.yaml'
homepage    | }
homepage    | Error: ENOENT: no such file or directory, open '/app/config/settings.yaml'
homepage    |     at Object.openSync (node:fs:600:3)
homepage    |     at readFileSync (node:fs:468:35)
homepage    |     at getSettings (/app/.next/server/chunks/4210.js:59:72)
homepage    |     at init (/app/.next/server/chunks/3471.js:32:93)
homepage    |     at createLogger (/app/.next/server/chunks/3471.js:99:5)
homepage    |     at /app/.next/server/chunks/5617.js:107:81 {
homepage    |   errno: -2,
homepage    |   syscall: 'open',
homepage    |   code: 'ENOENT',
homepage    |   path: '/app/config/settings.yaml'
homepage    | }
homepage    | Error: ENOENT: no such file or directory, open '/app/config/docker.yaml'
homepage    |     at Object.openSync (node:fs:600:3)
homepage    |     at readFileSync (node:fs:468:35)
homepage    |     at /app/.next/server/pages/api/hash.js:69:65
homepage    |     at Array.map (<anonymous>)
homepage    |     at handler (/app/.next/server/pages/api/hash.js:66:26)
homepage    |     at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:15)
homepage    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
homepage    |     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
homepage    |     at async Object.fn (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
homepage    |     at async Router.execute (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36) {
homepage    |   errno: -2,
homepage    |   syscall: 'open',
homepage    |   code: 'ENOENT',
homepage    |   path: '/app/config/docker.yaml'
homepage    | }
homepage    | docker.yaml was copied to the config folder
homepage    | services.yaml was copied to the config folder
homepage    | bookmarks.yaml was copied to the config folder
homepage    | [2023-02-24T12:03:11.403Z] error: undefined
homepage    | [2023-02-24T12:03:11.407Z] info: widgets.yaml was copied to the config folder
homepage    | [2023-02-24T12:03:11.409Z] error: undefined
homepage    | [2023-02-24T12:03:11.410Z] error: undefined
homepage    | [2023-02-24T12:03:11.411Z] error: undefined
homepage    | [2023-02-24T12:03:16.422Z] error: undefined
homepage    | [2023-02-24T12:03:16.430Z] error: undefined
homepage    | [2023-02-24T12:03:16.433Z] error: undefined
homepage    | [2023-02-24T12:03:26.165Z] error: undefined
homepage    | [2023-02-24T12:03:26.166Z] error: undefined
homepage    | [2023-02-24T12:03:26.166Z] error: undefined
homepage    | [2023-02-24T12:03:26.438Z] error: undefined
homepage    | [2023-02-24T12:03:26.497Z] error: undefined
homepage    | [2023-02-24T12:03:26.498Z] error: undefined
homepage    | [2023-02-24T12:03:26.499Z] error: undefined
homepage    | [2023-02-24T12:03:27.057Z] error: undefined
homepage    | [2023-02-24T12:03:27.057Z] error: undefined
homepage    | [2023-02-24T12:03:27.058Z] error: undefined
homepage    | [2023-02-24T12:03:27.228Z] error: undefined
homepage    | [2023-02-24T12:03:27.229Z] error: undefined
homepage    | [2023-02-24T12:03:27.229Z] error: undefined
homepage    | [2023-02-24T12:03:27.381Z] error: undefined
homepage    | [2023-02-24T12:03:27.381Z] error: undefined
homepage    | [2023-02-24T12:03:27.382Z] error: undefined
homepage    | [2023-02-24T12:03:27.522Z] error: undefined
homepage    | [2023-02-24T12:03:27.523Z] error: undefined
homepage    | [2023-02-24T12:03:27.523Z] error: undefined
homepage    | [2023-02-24T12:03:27.630Z] error: undefined
homepage    | [2023-02-24T12:03:27.630Z] error: undefined
homepage    | [2023-02-24T12:03:27.631Z] error: undefined
homepage    | [2023-02-24T12:03:32.647Z] error: undefined
homepage    | [2023-02-24T12:03:32.649Z] error: undefined
homepage    | Listening on port 3000
homepage    | [2023-02-24T12:03:38.008Z] error: <service-helpers> Error: ENOENT: no such file or directory, open '/app/config/kubernetes.yaml'
homepage    |     at Object.openSync (node:fs:600:3)
homepage    |     at readFileSync (node:fs:468:35)
homepage    |     at getKubeConfig (/app/.next/server/chunks/5617.js:31:70)
homepage    |     at servicesFromKubernetes (/app/.next/server/chunks/5617.js:228:92)
homepage    |     at servicesResponse (/app/.next/server/chunks/8317.js:99:227)
homepage    |     at async handler (/app/.next/server/pages/api/services.js:77:12)
homepage    |     at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
homepage    |     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
homepage    |     at async Object.fn (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
homepage    |     at async Router.execute (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
homepage    | [2023-02-24T12:03:38.009Z] error: Failed to discover services, please check kubernetes.yaml for errors or remove example entries.
homepage    | [2023-02-24T12:03:38.009Z] error: Error: ENOENT: no such file or directory, open '/app/config/kubernetes.yaml'

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I would be surprised to learn that based off of how the files are created, however, I’m on mobile right now so would have to verify that when I’m in front of my machine. In the meantime, have you tried deleting everything and re-creating?

**Comment by myhrmans** [comment]
I have. I have to manually create chown the files afterwards for them to match the PGIU and PGIU

**Comment by shamoon** [comment]
Yeah, I can't recreate this issue, works as expected, not sure what's up specifically with your setup

```
-rw-rw-r-- 1 1000 1000  357 Feb 24 21:55 bookmarks.yaml
-rw-rw-r-- 1 1000 1000  199 Feb 24 21:55 docker.yaml
-rw-rw-r-- 1 1000 1000   31 Feb 24 21:55 kubernetes.yaml
drwxr-xr-x 2 1000 1000 4096 Feb 24 21:55 logs
-rw-rw-r-- 1 1000 1000  452 Feb 24 21:55 services.yaml
-rw-rw-r-- 1 1000 1000  186 Feb 24 21:55 settings.yaml
-rw-rw-r-- 1 1000 1000  215 Feb 24 21:55 widgets.yaml
```
