### ISSUE TITLE
Updated and now webpage says 500: Internal Server Error

### ISSUE THREAD

**Issue by lukeeexd** [benphelps/homepage#106]
```
Sep 11 16:51:11 HomeServer systemd[1]: Stopping homepage Service...
Sep 11 16:51:11 HomeServer systemd[1]: homepage.service: Killing process 162158 (node) with signal SIGKILL.
Sep 11 16:51:11 HomeServer systemd[1]: homepage.service: Deactivated successfully.
Sep 11 16:51:11 HomeServer systemd[1]: Stopped homepage Service.
Sep 11 16:51:11 HomeServer systemd[1]: Started homepage Service.
Sep 11 16:51:11 HomeServer npm[162175]: > startpage@0.1.0 start
Sep 11 16:51:11 HomeServer npm[162175]: > next start
Sep 11 16:51:11 HomeServer npm[162188]: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Sep 11 16:51:11 HomeServer npm[162188]: warn  - You have enabled experimental feature (images) in next.config.js.
Sep 11 16:51:11 HomeServer npm[162188]: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
Sep 11 16:51:19 HomeServer npm[162188]: /opt/homepage/.next/server/pages/index.js:2716
Sep 11 16:51:19 HomeServer npm[162188]:   if (error || data?.error) {
Sep 11 16:51:19 HomeServer npm[162188]:                     ^
Sep 11 16:51:19 HomeServer npm[162188]: SyntaxError: Unexpected token '.'
Sep 11 16:51:19 HomeServer npm[162188]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
Sep 11 16:51:19 HomeServer npm[162188]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
Sep 11 16:51:19 HomeServer npm[162188]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Sep 11 16:51:19 HomeServer npm[162188]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Sep 11 16:51:19 HomeServer npm[162188]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Sep 11 16:51:19 HomeServer npm[162188]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Sep 11 16:51:19 HomeServer npm[162188]:     at require (internal/modules/cjs/helpers.js:74:18)
Sep 11 16:51:19 HomeServer npm[162188]:     at Object.requirePage (/opt/homepage/node_modules/next/dist/server/require.js:58:12)
Sep 11 16:51:19 HomeServer npm[162188]:     at /opt/homepage/node_modules/next/dist/server/load-components.js:56:50
Sep 11 16:51:19 HomeServer npm[162188]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sep 11 16:51:25 HomeServer npm[162188]: /opt/homepage/.next/server/pages/index.js:2716
Sep 11 16:51:25 HomeServer npm[162188]:   if (error || data?.error) {
Sep 11 16:51:25 HomeServer npm[162188]:                     ^
Sep 11 16:51:25 HomeServer npm[162188]: SyntaxError: Unexpected token '.'
Sep 11 16:51:25 HomeServer npm[162188]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
Sep 11 16:51:25 HomeServer npm[162188]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
Sep 11 16:51:25 HomeServer npm[162188]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Sep 11 16:51:25 HomeServer npm[162188]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Sep 11 16:51:25 HomeServer npm[162188]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Sep 11 16:51:25 HomeServer npm[162188]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Sep 11 16:51:25 HomeServer npm[162188]:     at require (internal/modules/cjs/helpers.js:74:18)
Sep 11 16:51:25 HomeServer npm[162188]:     at Object.requirePage (/opt/homepage/node_modules/next/dist/server/require.js:58:12)
Sep 11 16:51:25 HomeServer npm[162188]:     at /opt/homepage/node_modules/next/dist/server/load-components.js:56:50
Sep 11 16:51:25 HomeServer npm[162188]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sep 11 16:51:36 HomeServer systemd[1]: Stopping homepage Service...
Sep 11 16:51:36 HomeServer systemd[1]: homepage.service: Killing process 162194 (node) with signal SIGKILL.
Sep 11 16:51:36 HomeServer systemd[1]: homepage.service: Deactivated successfully.
Sep 11 16:51:36 HomeServer systemd[1]: Stopped homepage Service.
Sep 11 16:51:36 HomeServer systemd[1]: Started homepage Service.
Sep 11 16:51:36 HomeServer npm[162213]: > startpage@0.1.0 start
Sep 11 16:51:36 HomeServer npm[162213]: > next start
Sep 11 16:51:36 HomeServer npm[162225]: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Sep 11 16:51:36 HomeServer npm[162225]: warn  - You have enabled experimental feature (images) in next.config.js.
Sep 11 16:51:36 HomeServer npm[162225]: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
```

**Comment by lukeeexd** [comment]
Tried new install and same happens

**Comment by benphelps** [comment]
This looks like you're running it outside of the Docker environment, so make sure you've got the latest Node, as that's an error due to a missing JS language feature.

**Comment by lukeeexd** [comment]
> This looks like you're running it outside of the Docker environment, so make sure you've got the latest Node, as that's an error due to a missing JS language feature.

I'm running v18.7.0 do you know what the latest is?

**Comment by benphelps** [comment]
You can read about the language feature here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

It's reporting to be available as of Node.js 14.0.0

**Comment by lukeeexd** [comment]
So how can I have it missing then when I was on v0.1.6 of homepage just fine?

**Comment by benphelps** [comment]
That version probably was not using that language feature, so it was never an issue.  I'd make sure your Node.js version is correct when running it from systemd, it might be falling back to a system installed version, over a user or otherwise provided version.

**Comment by benphelps** [comment]
For reference, the Docker image builds using Node.js v18.9.0 and this is not an issue there.

**Comment by lukeeexd** [comment]
``.nvm/versions/node/v18.9.0/bin/npm start`` I specify the version in systemd

**Comment by lukeeexd** [comment]
So it works with ``yarn start`` but not from my systemd

**Comment by benphelps** [comment]
I'm going to convert this to a discussion, since it's a deployment issue and not a Homepage issue.
