### ISSUE TITLE
Unifi service doesn't work after update to 3.0.20

### ISSUE THREAD

**Issue by Markoudstaal** [benphelps/homepage#1452]
### Description

After Unifi OS was updated to 3.0.20 last night the integration on homepage no longer works.

![image](https://user-images.githubusercontent.com/7512733/235736257-1e396861-85f6-4bec-aa3a-8bae0cd99cd4.png)

### Steps to reproduce

1. Unifi OS updated to 3.0.20
2. Correct and previously working configuration for unifi in homepage. 

### homepage version

v0.6.17

### Installation method

Docker

### Container Logs

[2023-05-02T16:51:26.389Z] error: <httpProxy> [
  500,
  Error: connect EHOSTUNREACH 192.168.192.28:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.192.28',
    port: 443
  }
]
[2023-05-02T16:51:26.389Z] error: <unifiProxyHandler> HTTP 500 getting data from Unifi endpoint https://192.168.192.28/api/stat/sites. Data: { error: [Object] }
[2023-05-02T16:52:16.094Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://192.168.192.28/api/stat/sites. Data: Not Found

### Browser Logs

framework-7d66e48d1c14e56a.js:1 TypeError: Cannot read properties of undefined (reading 'message')
    at l (index-229d4695e41e3b85.js:1:2563)
    at Eo (framework-7d66e48d1c14e56a.js:1:63192)
    at xi (framework-7d66e48d1c14e56a.js:1:120432)
    at bs (framework-7d66e48d1c14e56a.js:1:109368)
    at gs (framework-7d66e48d1c14e56a.js:1:109296)
    at vs (framework-7d66e48d1c14e56a.js:1:109159)
    at as (framework-7d66e48d1c14e56a.js:1:105939)
    at ls (framework-7d66e48d1c14e56a.js:1:104490)
    at S (framework-7d66e48d1c14e56a.js:1:138447)
    at MessagePort.T (framework-7d66e48d1c14e56a.js:1:138981)
du @ framework-7d66e48d1c14e56a.js:1
index-229d4695e41e3b85.js:1 TypeError: Cannot read properties of undefined (reading 'message')
    at l (index-229d4695e41e3b85.js:1:2563)
    at Eo (framework-7d66e48d1c14e56a.js:1:63192)
    at xi (framework-7d66e48d1c14e56a.js:1:120432)
    at bs (framework-7d66e48d1c14e56a.js:1:109368)
    at gs (framework-7d66e48d1c14e56a.js:1:109296)
    at vs (framework-7d66e48d1c14e56a.js:1:109159)
    at as (framework-7d66e48d1c14e56a.js:1:105939)
    at ls (framework-7d66e48d1c14e56a.js:1:104490)
    at S (framework-7d66e48d1c14e56a.js:1:138447)
    at MessagePort.T (framework-7d66e48d1c14e56a.js:1:138981) Object
value @ index-229d4695e41e3b85.js:1

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
`EHOSTUNREACH 192.168.192.28:443`

Please post output from the troubleshooting guide https://gethomepage.dev/en/more/troubleshooting/#service-widget-errors

Unifi updating is always a roll of the dice but I'd be surprised if they totally broke their API. I think homepage cant communicate with your UDM

**Comment by Markoudstaal** [comment]
Should have been more thorough, restarting homepage container fixed it.
