### ISSUE TITLE
[Bug]: v0.6.18 - several issues

### ISSUE THREAD

**Issue by alexdelprete** [benphelps/homepage#1512]
### Description

I just upgraded from v0.6.17 to v0.6.18 and after recreating the container, I noticed several errors in the log, plus the background wouldn't load, the layout was all wrong (columns instead of configured rows layout), and 2 widgets weren't working anymore (nextdns and freshrss). I also noticed the CPU was high for too long and fans started kicking in. Usually that happens only for 2s while starting/refreshing homepage.

```
Listening on port 3000
[2023-05-17T19:10:40.198Z] error: undefined
[2023-05-17T19:10:40.463Z] error: undefined
[2023-05-17T19:11:47.862Z] error: undefined
[2023-05-17T19:11:47.864Z] error: undefined
```

I tried recreating the container several times, but it didn't solve the issue. Went back to .17 and everything's working perfectly again.

### Steps to reproduce

Upgrade container in docker-compose.yml fro v0.6.17 to v0.6.18.

### homepage version

v0.6.18

### Installation method

Docker

### Container Logs

```
Listening on port 3000
[2023-05-17T19:10:40.198Z] error: undefined
[2023-05-17T19:10:40.463Z] error: undefined
[2023-05-17T19:11:47.862Z] error: undefined
[2023-05-17T19:11:47.864Z] error: undefined
```

### Troubleshooting

All tests are ok.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
This is not particularly actionable. Those error logs are not new, and are not the issue. I am running .18 with a custom layout, background, etc so not seeing this

As for the specific widgets, again, would need more info but those weren't changed.

**Comment by alexdelprete** [comment]
> This is not particularly actionable. Those error logs are not new, and are not the issue.

What logs do you need to check? I can provide them. Those are the only things I see from the container's log.

**Comment by shamoon** [comment]
What about browser error console?

What exactly is the problem with the two widgets?

**Comment by alexdelprete** [comment]
Browser console:

```
Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.
content.js:7  Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Array.<anonymous> (content.js:7:88744)
    at c.trigger (content.js:7:81786)
    at HTMLDocument.<anonymous> (content.js:7:81311)
(anonymous) @ content.js:7
c.trigger @ content.js:7
(anonymous) @ content.js:7
Show 3 more frames
framework-7d66e48d1c14e56a.js:1 [Violation] 'message' handler took 300ms
homepage.osilife.net/:1 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
[Violation] Forced reflow while executing JavaScript took 70ms
content.js:7  Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at content.js:7:89004
(anonymous) @ content.js:7
setTimeout (async)
(anonymous) @ content.js:7
c.trigger @ content.js:7
(anonymous) @ content.js:7
ki @ framework-7d66e48d1c14e56a.js:1
bi @ framework-7d66e48d1c14e56a.js:1
yi @ framework-7d66e48d1c14e56a.js:1
(anonymous) @ framework-7d66e48d1c14e56a.js:1
ws @ framework-7d66e48d1c14e56a.js:1
ls @ framework-7d66e48d1c14e56a.js:1
S @ framework-7d66e48d1c14e56a.js:1
T @ framework-7d66e48d1c14e56a.js:1
Show 4 more frames
framework-7d66e48d1c14e56a.js:1  TypeError: f.slice is not a function
    at u (index-37fd0de46599dda2.js:1:4512)
    at Eo (framework-7d66e48d1c14e56a.js:1:63192)
    at xi (framework-7d66e48d1c14e56a.js:1:120432)
    at bs (framework-7d66e48d1c14e56a.js:1:109368)
    at gs (framework-7d66e48d1c14e56a.js:1:109296)
    at vs (framework-7d66e48d1c14e56a.js:1:109159)
    at as (framework-7d66e48d1c14e56a.js:1:105939)
    at is (framework-7d66e48d1c14e56a.js:1:106330)
    at jl (framework-7d66e48d1c14e56a.js:1:46913)
    at framework-7d66e48d1c14e56a.js:1:103872
du @ framework-7d66e48d1c14e56a.js:1
a.componentDidCatch.t.callback @ framework-7d66e48d1c14e56a.js:1
Ua @ framework-7d66e48d1c14e56a.js:1
ki @ framework-7d66e48d1c14e56a.js:1
bi @ framework-7d66e48d1c14e56a.js:1
yi @ framework-7d66e48d1c14e56a.js:1
(anonymous) @ framework-7d66e48d1c14e56a.js:1
ws @ framework-7d66e48d1c14e56a.js:1
is @ framework-7d66e48d1c14e56a.js:1
jl @ framework-7d66e48d1c14e56a.js:1
(anonymous) @ framework-7d66e48d1c14e56a.js:1
index-37fd0de46599dda2.js:1  TypeError: f.slice is not a function
    at u (index-37fd0de46599dda2.js:1:4512)
    at Eo (framework-7d66e48d1c14e56a.js:1:63192)
    at xi (framework-7d66e48d1c14e56a.js:1:120432)
    at bs (framework-7d66e48d1c14e56a.js:1:109368)
    at gs (framework-7d66e48d1c14e56a.js:1:109296)
    at vs (framework-7d66e48d1c14e56a.js:1:109159)
    at as (framework-7d66e48d1c14e56a.js:1:105939)
    at is (framework-7d66e48d1c14e56a.js:1:106330)
    at jl (framework-7d66e48d1c14e56a.js:1:46913)
    at framework-7d66e48d1c14e56a.js:1:103872 {componentStack: '\n    at u (https://homepage.osilife.net/_next/stat…t/static/chunks/main-28f0bf55ce641aab.js:1:11826)'}componentStack: "\n    at u (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:3888)\n    at c (https://homepage.osilife.net/_next/static/chunks/6649.6b531d7efd815fee.js:1:1106)\n    at h (https://homepage.osilife.net/_next/static/chunks/4121-c10f39ad3208a3b4.js:1:12201)\n    at n (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:11025)\n    at G (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:22331)\n    at div\n    at li\n    at R (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:25326)\n    at ul\n    at I (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:28933)\n    at div\n    at O (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:29296)\n    at div\n    at div\n    at re (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:43156)\n    at n (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:11025)\n    at https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88962\n    at te (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:41210)\n    at div\n    at div\n    at div\n    at ie (https://homepage.osilife.net/_next/static/chunks/pages/index-37fd0de46599dda2.js:1:47104)\n    at a (https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15091)\n    at s (https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15649)\n    at u (https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:14524)\n    at https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88962\n    at https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:13805\n    at l (https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:1462)\n    at n (https://homepage.osilife.net/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:6033)\n    at r (https://homepage.osilife.net/_next/static/chunks/main-28f0bf55ce641aab.js:1:6946)\n    at Y (https://homepage.osilife.net/_next/static/chunks/main-28f0bf55ce641aab.js:1:9186)\n    at ie (https://homepage.osilife.net/_next/static/chunks/main-28f0bf55ce641aab.js:1:11826)"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
value @ index-37fd0de46599dda2.js:1
a.componentDidCatch.t.callback @ framework-7d66e48d1c14e56a.js:1
Ua @ framework-7d66e48d1c14e56a.js:1
ki @ framework-7d66e48d1c14e56a.js:1
bi @ framework-7d66e48d1c14e56a.js:1
yi @ framework-7d66e48d1c14e56a.js:1
(anonymous) @ framework-7d66e48d1c14e56a.js:1
ws @ framework-7d66e48d1c14e56a.js:1
is @ framework-7d66e48d1c14e56a.js:1
jl @ framework-7d66e48d1c14e56a.js:1
(anonymous) @ framework-7d66e48d1c14e56a.js:1
index-37fd0de46599dda2.js:1 
        
        
        GET https://homepage.osilife.net/api/docker/status/webtop/docker2 404
fetcher @ index-37fd0de46599dda2.js:1
(anonymous) @ _app-8985fbb6b5c333d7.js:1
(anonymous) @ _app-8985fbb6b5c333d7.js:1
(anonymous) @ _app-8985fbb6b5c333d7.js:1
(anonymous) @ _app-8985fbb6b5c333d7.js:1
o @ _app-8985fbb6b5c333d7.js:1
(anonymous) @ _app-8985fbb6b5c333d7.js:1
(anonymous) @ _app-8985fbb6b5c333d7.js:1
ri @ framework-7d66e48d1c14e56a.js:1
ki @ framework-7d66e48d1c14e56a.js:1
bi @ framework-7d66e48d1c14e56a.js:1
yi @ framework-7d66e48d1c14e56a.js:1
(anonymous) @ framework-7d66e48d1c14e56a.js:1
ws @ framework-7d66e48d1c14e56a.js:1
ls @ framework-7d66e48d1c14e56a.js:1
S @ framework-7d66e48d1c14e56a.js:1
T @ framework-7d66e48d1c14e56a.js:1
```

**Comment by alexdelprete** [comment]
NextDNS widget:

![image](https://github.com/benphelps/homepage/assets/7027842/71abc7e6-a6a6-45f5-b8da-59518821df4d)

**Comment by shamoon** [comment]
Can you try `main` image?

This is likely the same as #1511

**Comment by alexdelprete** [comment]
Column layout while row is configured, and no background:

![image](https://github.com/benphelps/homepage/assets/7027842/66c11f8c-9745-410a-91a2-7f89a7f236af)

This is .17 layout:

![image](https://github.com/benphelps/homepage/assets/7027842/ca2e54a1-db41-4c3d-bbee-9ad4418061b2)

**Comment by shamoon** [comment]
I'll release .19 to fix this, thanks for your help

**Comment by alexdelprete** [comment]
Do I need to test the :main image?

**Comment by shamoon** [comment]
They're both building so wait for .19 (~20 minutes) and then let me know but Im pretty confident it will fix this

**Comment by alexdelprete** [comment]
No problem Ben, and thanks as always for the quick support. Will keep you posted.

**Comment by shamoon** [comment]
Not Ben :)

thanks

**Comment by alexdelprete** [comment]
> Not Ben :)
> 
> thanks

yeah...I edited my post before your comment. :D

**Comment by alexdelprete** [comment]
@shamoon .19 working fine. :)
