### ISSUE TITLE
[Bug] Using `ping: https://192.168.0.1` entry crashes homepage

### ISSUE THREAD

**Issue by MildlyInterested** [benphelps/homepage#1527]
### Description

Using the ping feature seems to occasionally crash the homepage.
I'm using it to ping my printer like so:
```yaml
    - Printer:
        href: http://192.168.0.7
        icon: hp
        ping: http://192.168.0.7
```
It does ping succesfully but it keeps reloading the hompage/restarting the container.

### Steps to reproduce

1. Edit services.yaml
2. Add a service with the `ping` feature.
3. Save and navigate to homgepage and reload.
4. Look at logs.

### homepage version

v0.6.20 (6046f79, May 19, 2023)

### Installation method

Docker

### Configuration

```yaml
- Hardware:
    - Printer:
        href: http://192.168.0.7
        icon: hp
        ping: http://192.168.0.7
```

### Container Logs

```
[2023-05-20T12:01:08.108Z] error: TypeError: Cannot read properties of null (reading 'setMaxAge')
    at /app/.next/server/chunks/4851.js:40:14
    at Array.map (<anonymous>)
    at addCookieToJar (/app/.next/server/chunks/4851.js:38:28)
    at IncomingMessage.<anonymous> (/app/.next/server/chunks/4851.js:110:77)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2023-05-20T12:01:08.110Z] error: TypeError: Cannot read properties of null (reading 'setMaxAge')
    at /app/.next/server/chunks/4851.js:40:14
    at Array.map (<anonymous>)
    at addCookieToJar (/app/.next/server/chunks/4851.js:38:28)
    at IncomingMessage.<anonymous> (/app/.next/server/chunks/4851.js:110:77)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Troubleshooting

Ping does complete and time is shown on homepage.

### Other

I've tried pinging different web services, happens with all of them.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I cant reproduce this nor are others reporting it but I suppose it's safe enough to wrap the code with a little more error handling. Unless this crops up more I dont think we will pursue beyond that. Thanks for reporting.
