### ISSUE TITLE
docker widget config "showStats: true" lead to page err

### ISSUE THREAD

**Issue by gasment** [benphelps/homepage#1764]
### Description

after add "showStats: true" to a docker container widget in services.yaml,
when the container is running ,everything fine.
but since the container stopped ,homepage cash with err info like this:
Something went wrong.
TypeError: Cannot read properties of undefined (reading 'widget')

i try to remove the config "showStats: true",then the problem solved
same problem since v0.6.25

downgrade to v0.6.23，it comes to nomal

### Steps to reproduce

1.add "showStats: true" to a docker container widget in services.yaml
2.when homepage goes fine,stop the container which config with "showStats: true"
3.flash homepage web,it comes to a err

### homepage version

v0.6.26

### Installation method

Docker

### Configuration

```yaml
- npm:
        icon: /icons/npm.png
        href: http://localhost/
        description: Nginx Proxy Manager
        server: dsm-docker
        container: npm
        showStats: true
```

### Browser Logs

framework-eda4609282c049ac.js:1  TypeError: Cannot read properties of undefined (reading 'widget')
    at u (index-a958623490fd081c.js:1:4420)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494)
    at S (framework-eda4609282c049ac.js:1:138467)

### Troubleshooting

framework-eda4609282c049ac.js:1  TypeError: Cannot read properties of undefined (reading 'widget')
    at u (index-a958623490fd081c.js:1:4420)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494)
    at S (framework-eda4609282c049ac.js:1:138467)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by 8ar10der** [comment]
Same here, but the error msg is `TypeError: Cannot read properties of undefined (reading 'cache')`

Version: v0.6.28 (63a5622)
Using Podman: 1.31.0

Browser Log:
```log
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
framework-eda4609282c049ac.js:1  TypeError: Cannot read properties of undefined (reading 'cache')
    at o (index-1719005733e841d3.js:1:55935)
    at d (index-1719005733e841d3.js:1:57221)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494)
du @ framework-eda4609282c049ac.js:1
index-1719005733e841d3.js:1  TypeError: Cannot read properties of undefined (reading 'cache')
    at o (index-1719005733e841d3.js:1:55935)
    at d (index-1719005733e841d3.js:1:57221)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494) ObjectcomponentStack: "\n    at d (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:56022)\n    at div\n    at div\n    at li\n    at z (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:29500)\n    at ul\n    at D (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:33242)\n    at div\n    at https://home.amao.run/_next/static/chunks/3230-1ff23c8d07248148.js:1:43993\n    at div\n    at l (https://home.amao.run/_next/static/chunks/3230-1ff23c8d07248148.js:1:70124)\n    at https://home.amao.run/_next/static/chunks/3230-1ff23c8d07248148.js:1:62738\n    at https://home.amao.run/_next/static/chunks/3230-1ff23c8d07248148.js:1:61683\n    at l (https://home.amao.run/_next/static/chunks/3230-1ff23c8d07248148.js:1:70124)\n    at https://home.amao.run/_next/static/chunks/3230-1ff23c8d07248148.js:1:41939\n    at div\n    at I (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:33623)\n    at div\n    at div\n    at le (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:50069)\n    at n (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:14142)\n    at https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:89083\n    at oe (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:48076)\n    at div\n    at div\n    at div\n    at de (https://home.amao.run/_next/static/chunks/pages/index-1719005733e841d3.js:1:54310)\n    at a (https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:15149)\n    at s (https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:15711)\n    at u (https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:14577)\n    at https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:89083\n    at https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:13854\n    at l (https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:1471)\n    at n (https://home.amao.run/_next/static/chunks/pages/_app-9c9825a58ffa33a1.js:1:6048)\n    at r (https://home.amao.run/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)\n    at Y (https://home.amao.run/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)\n    at ie (https://home.amao.run/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
value @ index-1719005733e841d3.js:1
```
