### ISSUE TITLE
[Bug] Proxmox Backup Server Widget not working

### ISSUE THREAD

**Issue by urbaman** [benphelps/homepage#1907]
### Description

I am trying to make the widget work, to no avail.

Deployment on kubernetes.

I think everything from the PBS side is worikng (permissions/tokens), but something else is happening, as this is what I get from the widget inside homepage.

```
Cannot read properties of undefined (reading 'used')

    at l (https://gethomepage.urbaman.it/_next/static/chunks/8229.2f628bf62d35251d.js:1:1088)
    at h (https://gethomepage.urbaman.it/_next/static/chunks/8851-2e733d9d318b32dc.js:1:12200)
    at n (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:9932)
    at G (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:19775)
    at div
    at li
    at R (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:22808)
    at ul
    at O (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:26358)
    at div
    at D (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:26645)
    at div
    at div
    at re (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:40268)
    at n (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:9932)
    at https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:88005
    at te (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:38322)
    at div
    at div
    at ie (https://gethomepage.urbaman.it/_next/static/chunks/pages/index-c212e5840c40d46c.js:1:44112)
    at a (https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:15041)
    at s (https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:15598)
    at u (https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:14473)
    at https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:88005
    at https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:13754
    at l (https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:1461)
    at n (https://gethomepage.urbaman.it/_next/static/chunks/pages/_app-91b11616c0a3265e.js:1:5971)
    at r (https://gethomepage.urbaman.it/_next/static/chunks/main-d2b206db40ae9853.js:1:6948)
    at Y (https://gethomepage.urbaman.it/_next/static/chunks/main-d2b206db40ae9853.js:1:9190)
    at ie (https://gethomepage.urbaman.it/_next/static/chunks/main-d2b206db40ae9853.js:1:11830)
```

### Steps to reproduce

Just apply the PBS widget, PBS is last version, permission is "Audit"

      - Proxmox Backup Server:
          description: Proxmox Backup Server
          href: https://pbs1.domain.com:8007
          widget:
            type: proxmoxbackupserver
            url: https://pbs1.domain.com:8007
            username: tokenid
            password: tokensecret

### homepage version

0.6.10

### Installation method

Other (please describe above)

### Configuration

```yaml
See above
```

### Container Logs

```
[2023-09-03T16:33:02.157Z] warn: API response for /api/services/proxy?type=prometheus&group=Monitoring&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[2023-09-03T16:33:04.610Z] warn: API response for /api/services/proxy?type=prometheus&group=Monitoring&service=Prometheus&endpoint=targets exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
```

### Troubleshooting

I already applyed permissions/tokens to users with Audit permisisons on PBS for other projects, and they work (Prometheus/Grafana monitoring of PBS), 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please provide the API response (you can look in the browser network tab)

**Comment by urbaman** [comment]
Hi, I see three requests:

```
request:
type=proxmoxbackupserver&group=Management&service=Proxmox+Backup+Server&endpoint=status%2Fdatastore-usage
response:
{"data":[]}
```

```
request:;
type=proxmoxbackupserver&group=Management&service=Proxmox+Backup+Server&endpoint=nodes%2Flocalhost%2Ftasks
response:
{"total":0,"data":[]}
```

```
request:
type=proxmoxbackupserver&group=Management&service=Proxmox+Backup+Server&endpoint=nodes%2Flocalhost%2Fstatus
response:
{
    "data": {
        "cpu": 0.0036681950812839093,
        "cpuinfo": {
            "cpus": 12,
            "model": "Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz",
            "sockets": 1
        },
        "info": {
            "fingerprint": "fingerprint"
        },
        "kversion": "Linux 6.2.16-10-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-10 (2023-08-18T11:42Z)",
        "loadavg": [
            0.07,
            0.09,
            0.02
        ],
        "memory": {
            "free": 23020175360,
            "total": 25019404288,
            "used": 1999228928
        },
        "root": {
            "avail": 222679269376,
            "total": 232441511936,
            "used": 9762242560
        },
        "swap": {
            "free": 0,
            "total": 0,
            "used": 0
        },
        "uptime": 109568,
        "wait": 0.0
    }
}
```

**Comment by shamoon** [comment]
Thanks. Your `nodes` and `status` endpoints aren’t returning anything. I don’t have PBS so I don’t know if that’s normal for your setup or things aren’t setup right. I’d guess the latter, but if it’s the former the fix would mean in your case the widget would lop off a couple of the fields

**Comment by urbaman** [comment]
Ok, thank you.

I'd say the same settings I use for the prometheus exporter would suffice, I'll double check the proxmox backup server api docs and try to fix it, and then I'll be back with my findings.

**Comment by urbaman** [comment]
Ok, I can confirm there are no problems on PBS conf/usage, as I can access all three api nodes directly from the browser, and the data are there.

Still trying to debug why I gat null data from the homepage, I'm also checking with the proxmox community, and will get back with info and insight asap.
