### ISSUE TITLE
Unable to start homepage in Docker: TypeError: handler is not a function

### ISSUE THREAD

**Issue by jackblk** [benphelps/homepage#26]
Docker command:
`docker run --rm -it -p 3000:3000 -v $(pwd)/homepage/config:/app/config -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/benphelps/homepage:main`

http://localhost:3000/ will return internal server error

Docker logs:

```
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by ThisIsNoahEvans** [comment]
Getting this same issue. Used the following Docker Compose:

```
version: '3.3'
services:
    homepage:
        image: ghcr.io/benphelps/homepage:main
        container_name: homepage
        ports:
            - 1000:3000
        volumes:
            - /var/lib/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations  
```

With the following log output:
```
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17),
TypeError: handler is not a function,
    at Server.<anonymous> (/app/server.js:19:11),
    at Server.emit (node:events:513:28),
    at parserOnIncoming (node:_http_server:980:12),
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by benphelps** [comment]
This will be resolved as soon as the latest image finishes building.  Apparently Next.js fails to start the server with a symlink existing in the public/ folder.
