### ISSUE TITLE
Exception when container has "host" network

### ISSUE THREAD

**Issue by wjbridge** [benphelps/homepage#31]
First off, awesome work @benphelps! I wanted to report an issue that if the container is `network: host` an exception occurs when you click on the green indicator light.

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Browser Console
```
framework-b3ca2e9a9574e304.js:1 
    TypeError: Cannot read properties of undefined (reading 'eth0')
    at N (index-19044850d7adb1f3.js:1:3883)
    at Eo (framework-b3ca2e9a9574e304.js:1:63191)
    at Pu (framework-b3ca2e9a9574e304.js:1:74879)
    at xi (framework-b3ca2e9a9574e304.js:1:121314)
    at bs (framework-b3ca2e9a9574e304.js:1:109367)
    at gs (framework-b3ca2e9a9574e304.js:1:109295)
    at vs (framework-b3ca2e9a9574e304.js:1:109158)
    at as (framework-b3ca2e9a9574e304.js:1:105938)
    at ls (framework-b3ca2e9a9574e304.js:1:104489)
    at S (framework-b3ca2e9a9574e304.js:1:138448)
```

**Comment by benphelps** [comment]
Thanks for reporting, I'll check it out.

**Comment by benphelps** [comment]
This has been fixed, you can grab it right now from the `main` Docker tag, or wait until the next release to grab it from `latest`.
