### ISSUE TITLE
[Bug] application error

### ISSUE THREAD

**Issue by kraizelburg** [benphelps/homepage#322]
**Describe the bug**
after having homepage open after 3-5 min page goes blank and display the following message "Application error: a client-side exception has occurred (see the browser console for more information"
Reffreshing the page solves the problem but it occurs again after a few mins
**Expected behavior**

**Screenshots**

**Configuration**
If applicable,
```yaml
# Please provide your service, widget or otherwise related configuration here
```

**Additional context**
Add any other context about the problem here. This includes things like:
 - Service version or API version: v0.4.0 (de4ce73, Oct 1, 2022)
 - Docker version: Docker version 20.10.12, build 20.10.12-0ubuntu4
 - Deployment method: docker-compose
 - Sample YAML configurations

**Comment by JazzFisch** [comment]
Can you please provide the information in the `Additional context` section of your report?  Also, can you provide the config/logs/homepage.log file?

**Comment by joevaughan** [comment]
Experiencing the same issue (Chromium based browsers - 2 of, Chrome itself and Vivaldi). 

System log at the time (config/logs/homepage.log) shows only this error which happens some times and I don't think is related. 
`[2022-10-02T21:19:12.499Z] error: (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use "node --trace-warnings ..." to show where the warning was created)
[2022-10-02T21:19:12.935Z] error: <httpProxy> Error calling http://hostie/api/speedtest/latest...
[2022-10-02T21:19:12.938Z] error: <httpProxy> [
  500,
  Error: socket hang up
      at connResetException (node:internal/errors:711:14)
      at Socket.socketOnEnd (node:_http_client:518:23)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
]`

Console log from the browser seems to point at a client-side/Next.js issue perhaps?:
 
`Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (framework-c4881a94a5d6a5c8.js:1:43705)
    at qu (framework-c4881a94a5d6a5c8.js:1:85317)
    at ks (framework-c4881a94a5d6a5c8.js:1:109548)
    at bs (framework-c4881a94a5d6a5c8.js:1:109429)
    at gs (framework-c4881a94a5d6a5c8.js:1:109296)
    at vs (framework-c4881a94a5d6a5c8.js:1:109159)
    at ls (framework-c4881a94a5d6a5c8.js:1:104263)
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
6framework-c4881a94a5d6a5c8.js:1 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sa (framework-c4881a94a5d6a5c8.js:1:48561)
    at xi (framework-c4881a94a5d6a5c8.js:1:122126)
    at bs (framework-c4881a94a5d6a5c8.js:1:109368)
    at gs (framework-c4881a94a5d6a5c8.js:1:109296)
    at vs (framework-c4881a94a5d6a5c8.js:1:109159)
    at ls (framework-c4881a94a5d6a5c8.js:1:104263)
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
framework-c4881a94a5d6a5c8.js:1 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (framework-c4881a94a5d6a5c8.js:1:121812)
    at bs (framework-c4881a94a5d6a5c8.js:1:109368)
    at gs (framework-c4881a94a5d6a5c8.js:1:109296)
    at vs (framework-c4881a94a5d6a5c8.js:1:109159)
    at as (framework-c4881a94a5d6a5c8.js:1:105939)
    at ls (framework-c4881a94a5d6a5c8.js:1:104490)
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
:1337/api/services/proxy?type=speedtest&group=Network&service=Speedtest&endpoint=speedtest%2Flatest:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
framework-c4881a94a5d6a5c8.js:1 TypeError: Cannot read properties of undefined (reading 'download')
    at u (9192.7d01bab6586304d3.js:1:1141)
    at Eo (framework-c4881a94a5d6a5c8.js:1:63192)
    at Pu (framework-c4881a94a5d6a5c8.js:1:74880)
    at xi (framework-c4881a94a5d6a5c8.js:1:121315)
    at bs (framework-c4881a94a5d6a5c8.js:1:109368)
    at gs (framework-c4881a94a5d6a5c8.js:1:109296)
    at vs (framework-c4881a94a5d6a5c8.js:1:109159)
    at as (framework-c4881a94a5d6a5c8.js:1:105939)
    at ls (framework-c4881a94a5d6a5c8.js:1:104490)
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
du @ framework-c4881a94a5d6a5c8.js:1
main-d2b206db40ae9853.js:1 TypeError: Cannot read properties of undefined (reading 'download')
    at u (9192.7d01bab6586304d3.js:1:1141)
    at Eo (framework-c4881a94a5d6a5c8.js:1:63192)
    at Pu (framework-c4881a94a5d6a5c8.js:1:74880)
    at xi (framework-c4881a94a5d6a5c8.js:1:121315)
    at bs (framework-c4881a94a5d6a5c8.js:1:109368)
    at gs (framework-c4881a94a5d6a5c8.js:1:109296)
    at vs (framework-c4881a94a5d6a5c8.js:1:109159)
    at as (framework-c4881a94a5d6a5c8.js:1:105939)
    at ls (framework-c4881a94a5d6a5c8.js:1:104490)
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
Q @ main-d2b206db40ae9853.js:1
main-d2b206db40ae9853.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Q @ main-d2b206db40ae9853.js:1
framework-c4881a94a5d6a5c8.js:1 TypeError: Cannot read properties of null (reading 'classList')
    at l (_app-fc77031352f30888.js:1:74005)
    at _app-fc77031352f30888.js:1:74133
    at ri (framework-c4881a94a5d6a5c8.js:1:93730)
    at Ss (framework-c4881a94a5d6a5c8.js:1:113957)
    at framework-c4881a94a5d6a5c8.js:1:110547
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
du @ framework-c4881a94a5d6a5c8.js:1
main-d2b206db40ae9853.js:1 TypeError: Cannot read properties of null (reading 'classList')
    at l (_app-fc77031352f30888.js:1:74005)
    at _app-fc77031352f30888.js:1:74133
    at ri (framework-c4881a94a5d6a5c8.js:1:93730)
    at Ss (framework-c4881a94a5d6a5c8.js:1:113957)
    at framework-c4881a94a5d6a5c8.js:1:110547
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
Q @ main-d2b206db40ae9853.js:1
main-d2b206db40ae9853.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Q @ main-d2b206db40ae9853.js:1
framework-c4881a94a5d6a5c8.js:1 TypeError: Cannot read properties of null (reading 'classList')
    at f (_app-fc77031352f30888.js:1:72867)
    at _app-fc77031352f30888.js:1:73019
    at ri (framework-c4881a94a5d6a5c8.js:1:93730)
    at Ss (framework-c4881a94a5d6a5c8.js:1:113957)
    at framework-c4881a94a5d6a5c8.js:1:110547
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
du @ framework-c4881a94a5d6a5c8.js:1
main-d2b206db40ae9853.js:1 TypeError: Cannot read properties of null (reading 'classList')
    at f (_app-fc77031352f30888.js:1:72867)
    at _app-fc77031352f30888.js:1:73019
    at ri (framework-c4881a94a5d6a5c8.js:1:93730)
    at Ss (framework-c4881a94a5d6a5c8.js:1:113957)
    at framework-c4881a94a5d6a5c8.js:1:110547
    at S (framework-c4881a94a5d6a5c8.js:1:138449)
    at MessagePort.T (framework-c4881a94a5d6a5c8.js:1:138983)
Q @ main-d2b206db40ae9853.js:1
main-d2b206db40ae9853.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Q @ main-d2b206db40ae9853.js:1
main-d2b206db40ae9853.js:1 Error rendering page:  Error: Cancel rendering route
    at U (main-d2b206db40ae9853.js:1:12278)
    at main-d2b206db40ae9853.js:1:12218
    at new Promise (<anonymous>)
    at ue (main-d2b206db40ae9853.js:1:12188)
    at main-d2b206db40ae9853.js:1:10697
`

(Sorry Github is munging the cpnsole error text - have attached as a TXT file also) 
[homepage-console-error.txt](https://github.com/benphelps/homepage/files/9693629/homepage-console-error.txt)

**Comment by benphelps** [comment]
Does your Speedtest widget actually show information?  The error happens because of a problem making the API requests to your speedtest container.

**Comment by joevaughan** [comment]
> 
Yep. Looks like it occasionally times out (don't know why that's happening - homepage and it are literally on the same machine) but seems to be fine. 

Maybe the above is a red-herring and it's not the speedtest widget causing the 'client side crash'. Just wanted to provide what more information I could. 

Note: this is definitely only happening since 0.4.0 - Never saw this error on the earlier versions. 

P.S. Loving the app :D

**Comment by tnagels** [comment]
I have the same issue. Working installation, upgraded and now I get an application error. Will try to get the logs asap.

**Comment by joevaughan** [comment]
For the absence of doubt. Here's what appears on the browser: 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/92576588/193555777-9b6f7d63-7910-49bf-9254-8f6741965b30.png">

**Comment by kraizelburg** [comment]
> For the absence of doubt. Here's what appears on the browser:
> 
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/92576588/193555777-9b6f7d63-7910-49bf-9254-8f6741965b30.png">

I get exactly same screen just after a few mins. I don't have speedtest container enabled.

**Comment by qubao347636681** [comment]
I also encountered this problem,
Delete widget: weather
Solved

**Comment by kraizelburg** [comment]
> 

I don't have weather widget enabled and still happening this bug.

**Comment by GertJanH** [comment]
I had the same error this morning, but this was the first time since 0.40 and I've been running it since its release. and the page is actually open all day.

widgets i usage

- portainer 3 times
- nginx proxy mananger 2 times
- pihole 2 times
- gotify
- emby
- transmission
- sonarr
- jackett
- bazarr

and the openweathermap weather widget

**Comment by joevaughan** [comment]
> I've had this error when I setup speedtest widget with missing/wrong values.

Speedtest is almost definitely a red-herring. My widget is operating fine. For other people it's the weather info-widget that causes this, for still others, neither of the above.

**Comment by kraizelburg** [comment]
Hi, I can confirm latest version 0.4.4 fixed the issue. thanks
