### ISSUE TITLE
Error: Unable to resolve path to module 'next-i18next'.  import/no-unresolved

### ISSUE THREAD

**Issue by chuckiton** [benphelps/homepage#352]
**Describe the bug**
After git pull and yarn install of latest verision,  yarn fails to build Homepage with the following errors:
```
Failed to compile.

./src/components/services/widget/block.jsx
1:32  Error: Unable to resolve path to module 'next-i18next'.  import/no-unresolved
```
this error is repeated for a number of different files.

**Expected behavior**
Yarn builds without error and I can launch homepage.

**Additional context**
Running on debian 11 on RPi using Yarn and systemd.

**Comment by chuckiton** [comment]
here is the error log if I try to `yarn start` after the failed build:
```ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Cannot find module 'i18next-browser-languagedetector'
Require stack:
- /home/Charlie/homepage/.next/server/pages/_app.js
- /home/Charlie/homepage/node_modules/next/dist/server/require.js
- /home/Charlie/homepage/node_modules/next/dist/server/next-server.js
- /home/Charlie/homepage/node_modules/next/dist/server/next.js
- /home/Charlie/homepage/node_modules/next/dist/server/lib/start-server.js
- /home/Charlie/homepage/node_modules/next/dist/cli/next-start.js
- /home/Charlie/homepage/node_modules/next/dist/lib/commands.js
- /home/Charlie/homepage/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/home/Charlie/homepage/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.mod._resolveFilename (/home/Charlie/homepage/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.6071 (/home/Charlie/homepage/.next/server/pages/_app.js:131:18)
    at __webpack_require__ (/home/Charlie/homepage/.next/server/webpack-runtime.js:25:42)
    at /home/Charlie/homepage/.next/server/pages/_app.js:74:90
    at Function.__webpack_require__.a (/home/Charlie/homepage/.next/server/webpack-runtime.js:89:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/Charlie/homepage/.next/server/pages/_app.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/require.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/next-server.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/next.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/lib/start-server.js',
    '/home/Charlie/homepage/node_modules/next/dist/cli/next-start.js',
    '/home/Charlie/homepage/node_modules/next/dist/lib/commands.js',
    '/home/Charlie/homepage/node_modules/next/dist/bin/next'
  ]
}
Error: Cannot find module 'i18next-browser-languagedetector'
Require stack:
- /home/Charlie/homepage/.next/server/pages/_app.js
- /home/Charlie/homepage/node_modules/next/dist/server/require.js
- /home/Charlie/homepage/node_modules/next/dist/server/next-server.js
- /home/Charlie/homepage/node_modules/next/dist/server/next.js
- /home/Charlie/homepage/node_modules/next/dist/server/lib/start-server.js
- /home/Charlie/homepage/node_modules/next/dist/cli/next-start.js
- /home/Charlie/homepage/node_modules/next/dist/lib/commands.js
- /home/Charlie/homepage/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/home/Charlie/homepage/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.mod._resolveFilename (/home/Charlie/homepage/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.6071 (/home/Charlie/homepage/.next/server/pages/_app.js:131:18)
    at __webpack_require__ (/home/Charlie/homepage/.next/server/webpack-runtime.js:25:42)
    at /home/Charlie/homepage/.next/server/pages/_app.js:74:90
    at Function.__webpack_require__.a (/home/Charlie/homepage/.next/server/webpack-runtime.js:89:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/Charlie/homepage/.next/server/pages/_app.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/require.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/next-server.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/next.js',
    '/home/Charlie/homepage/node_modules/next/dist/server/lib/start-server.js',
    '/home/Charlie/homepage/node_modules/next/dist/cli/next-start.js',
    '/home/Charlie/homepage/node_modules/next/dist/lib/commands.js',
    '/home/Charlie/homepage/node_modules/next/dist/bin/next'
  ]
}
```

**Comment by benphelps** [comment]
You probably need to remove your yarn lock file, homepage doesn't use yarn, so it ships with a pnpm lock file.
