### ISSUE TITLE
Failed to compile with pnpm on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by FabulousSoldier** [benphelps/homepage#422]
**Describe the bug**
I am trying to run homepage with Node on Ubuntu.
I followed the instructions but when I try to build the production bundle with pnpm it fails to compile:

```
user@Ubuntu:~/homepage$ pnpm build

> startpage@0.1.0 build /home/user/homepage
> next build


Failed to compile.

./src/utils/logger.js
2:1  Error: There should be at least one empty line between import groups  import/order
3:1  Error: There should be no empty line within import group  import/order
3:38  Error: Unable to resolve path to module 'node:util'.  import/no-unresolved

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types . ELIFECYCLE  Command failed with exit code 1.
```

**Expected behavior**
Should compile without errors.

**Additional context**
Same thing happens when I try to build it with npm. "pnpm install" works as expected.

I am running Ubuntu 22.04.1 LTS
Deployment method: Node

**Comment by FabulousSoldier** [comment]
Part of the problem seems to be an old version of node (v12.22.9) in Ubuntu. 
After updating to v16.18.0 I am able to successfully compile but I am still getting a time out error: 

```
user@Ubuntu:~/homepage$ pnpm build

> startpage@0.1.0 build /home/user/homepage
> next build

info  - Linting and checking validity of types
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/user/homepage/.babelrc
info  - Creating an optimized production build
info  - Compiled successfully
warn  - Restarted collecting page data for [object Object] because it took more than 60 seconds
warn  - See more info here https://nextjs.org/docs/messages/static-page-generation-timeout

> Build error occurred
Error: Collecting page data for [object Object] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
    at onRestart (/home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:593:35)
    at Worker.isPageStatic (/home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/lib/worker.js:48:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:705:52
    at async Span.traceAsyncFn (/home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async Promise.all (index 20)
    at async /home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:652:17
    at async Span.traceAsyncFn (/home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/user/homepage/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:617:170
info  - Collecting page data . ELIFECYCLE  Command failed with exit code 1.
```

As suggested in the error message I updated staticPageGenerationTimeout in next.config.js to 1000 seconds.
But I am still stuck at "Collecting page data"
