### ISSUE TITLE
[Bug] 500 error disk resources widget: Disk name invalid and / not found

### ISSUE THREAD

**Issue by RichyHBM** [benphelps/homepage#739]
### Description

It seems at times when using the docker image ghcr.io/benphelps/homepage:latest, and having assigned volumes to it, these do nmot work and an error is shown for each, looking at the logs it prints out the following for each request. I cant confirm exactly but this seems to have appeared since 0.5.5, or atleast it has been more common since then. It also does seem to work sometimes, so might be a race condition issue?

Compose volumes:
```
volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #
      - /home/pi:/media/sda:ro     #Server OS drive
      - /home/pi/usb:/media/sdb:ro     #External drive for additional storage
```

### Steps to reproduce

Unable to repro consistently

### homepage version

v0.5.7 (9f63a5a, 26 Dec 2022)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: false
    disk:
        - /media/sda
        - /media/sdb

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
        dateStyle: short
        timeStyle: short
        hour12: true

- openmeteo:
    # Hidden
```

### Container Logs

```
28/12/2022 14:04:57
Error: disk name invalid and / not found
28/12/2022 14:04:57
    at /app/node_modules/.pnpm/node-os-utils@1.3.7/node_modules/node-os-utils/lib/drive.js:62:17
28/12/2022 14:04:57
    at async handler (/app/.next/server/pages/api/widgets/resources.js:56:14)
28/12/2022 14:04:57
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
28/12/2022 14:04:57
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
28/12/2022 14:04:57
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
28/12/2022 14:04:57
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
28/12/2022 14:04:57
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:347:29)
28/12/2022 14:04:57
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:285:20)
28/12/2022 14:04:57
    at async Server.<anonymous> (/app/server.js:19:5)
28/12/2022 14:05:03
Error: disk name invalid and / not found
28/12/2022 14:05:03
    at /app/node_modules/.pnpm/node-os-utils@1.3.7/node_modules/node-os-utils/lib/drive.js:62:17
28/12/2022 14:05:03
    at async handler (/app/.next/server/pages/api/widgets/resources.js:56:14)
28/12/2022 14:05:03
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
28/12/2022 14:05:03
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
28/12/2022 14:05:03
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
28/12/2022 14:05:03
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
28/12/2022 14:05:03
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:347:29)
28/12/2022 14:05:03
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:285:20)
28/12/2022 14:05:03
    at async Server.<anonymous> (/app/server.js:19:5)
28/12/2022 14:05:03
Error: disk name invalid and / not found
28/12/2022 14:05:03
    at /app/node_modules/.pnpm/node-os-utils@1.3.7/node_modules/node-os-utils/lib/drive.js:62:17
28/12/2022 14:05:03
    at async handler (/app/.next/server/pages/api/widgets/resources.js:56:14)
28/12/2022 14:05:03
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
28/12/2022 14:05:03
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
28/12/2022 14:05:03
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
28/12/2022 14:05:03
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
28/12/2022 14:05:03
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:347:29)
28/12/2022 14:05:03
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:285:20)
28/12/2022 14:05:03
    at async Server.<anonymous> (/app/server.js:19:5)
28/12/2022 14:05:03
Error: disk name invalid and / not found
28/12/2022 14:05:03
    at /app/node_modules/.pnpm/node-os-utils@1.3.7/node_modules/node-os-utils/lib/drive.js:62:17
28/12/2022 14:05:03
    at async handler (/app/.next/server/pages/api/widgets/resources.js:56:14)
28/12/2022 14:05:03
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
28/12/2022 14:05:03
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:481:9)
28/12/2022 14:05:03
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:735:37)
28/12/2022 14:05:03
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
28/12/2022 14:05:03
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:347:29)
28/12/2022 14:05:03
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:285:20)
28/12/2022 14:05:03
    at async Server.<anonymous> (/app/server.js:19:5)
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I’m guessing this is an issue with your drive looks to be a removable (?) ie a mount issue but anyway, nothing about this is changed recently in the data comes basically directly from node-os-utils so I don’t really see there’s something to fix for us here
