### ISSUE TITLE
[Bug] Jellyfin: TypeError: Cannot read properties of undefined (reading 'MediaSources')

### ISSUE THREAD

**Issue by wjbridge** [benphelps/homepage#81]
Awesome work lately @benphelps! Another error to report. Using the "latest" docker tag and was playing a show via Jellyfin and this error popped up. I am using the Jellyfin widget.

## Using Image:

`ghcr.io/benphelps/homepage:latest@sha256:5314689c255705e71615030534e1efdfd0356def9daa32b604666ecf1fe27e59`

## Error in Browser Console
```
framework-b3ca2e9a9574e304.js:1 TypeError: Cannot read properties of undefined (reading 'MediaSources')
    at index-eb06fe45eb940f9e.js:1:6901
    at Array.reduce (<anonymous>)
    at jellyfin (index-eb06fe45eb940f9e.js:1:6840)
    at Eo (framework-b3ca2e9a9574e304.js:1:63191)
    at Pu (framework-b3ca2e9a9574e304.js:1:74879)
    at xi (framework-b3ca2e9a9574e304.js:1:121314)
    at bs (framework-b3ca2e9a9574e304.js:1:109367)
    at gs (framework-b3ca2e9a9574e304.js:1:109295)
    at vs (framework-b3ca2e9a9574e304.js:1:109158)
    at as (framework-b3ca2e9a9574e304.js:1:105938)
```

**Comment by benphelps** [comment]
The API from Jellyfin is all over the place with what data it gives back, and doesn't even properly support reporting back on two streams being played at the same time.

As an aside, I'm working on a new widget for Emby, Jellyfin and Plex, that I feel gives much better info:

<img width="412" alt="Screenshot 2022-09-10 at 12 39 42 PM" src="https://user-images.githubusercontent.com/82196/189477833-e4540845-63d9-4b43-811d-9ce30d5225eb.png">
